### PR TITLE
Adds scoped slots to slides

### PR DESCRIPTION
**Pull request by dobromir-hristov**
We have indices passed as cope props, and current position classes so users can apply styling or do changes depending where a slide is in the slider.

### CODE REVIEW

**Comment by dobromir-hristov** [comment]
This should do the trick.

**Comment by dobromir-hristov** [comment]
@Wlada want anything else?

**Comment by Wlada** [comment]
Hi,

No, sorry, all good. I’ll check everything and merge code first thing tomorrow morning.
Had couple of hard days and didn’t get time to check.

Sent from my iPhone

**Comment by Wlada** [comment]
Merged to master under version 0.1.21. Thanks!

**Pull request merged**
